import type { Metadata } from "next"
import "./globals.css"
import { UserProvider } from "@/context/userContext"
import AuthLayout from "@/layout/authLayout"
import HeaderLayout from "@/layout/headerLayout"
import type { ReactNode } from "react"

export const metadata: Metadata = {
  title: "Lootopia",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="fr">
      <body className="antialiased">
        <UserProvider>
          <AuthLayout>
            <HeaderLayout>{children}</HeaderLayout>
          </AuthLayout>
        </UserProvider>
      </body>
    </html>
  )
}
