import type { Metadata } from "next"
import "./globals.css"
import type { ReactNode } from "react"
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="fr">
    <Header></Header>
      <body className=" antialiased">{children}</body>
    </html>
  )
}
