services:
  gateway-service:
    platform: linux/amd64
    build:
      context: ./services/gateway
    image: lootopia_gateway_service
    ports:
      - "3000:3000"
    volumes:
      - ./services/gateway:/app
    env_file:
      - ./services/gateway/.env

  user-service:
    platform: linux/amd64
    build:
      context: ./services/user
    image: lootopia_user_service
    ports:
      - "3000:3000"
    volumes:
      - ./services/user:/app
    env_file:
      - ./services/user/.env

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    image: lootopia_frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
