services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    image: lootopia_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
    image: lootopia_frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
