services:
  backend:
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run start:dev"

  frontend:
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
